spring:
  application:
    name: gateway-service

server:
    port: 8762

jwt:
  secret-key: qwertyuiopasqwertyuiopasqwertyuiopas
  expired-in: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/