spring:
  application:
    name: hotel-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_management
    username: postgres
    password: Z43kFfa2xSZE3AtZUdS%
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 9500
  servlet:
    context-path: /hotel-management

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/